### ISSUE TITLE
Screen refresh lag

### ISSUE THREAD

**Issue by kinleyd** [project-repo/cagebreak#10]
I'm using v. 1.8.1 and am experiencing a screen refresh lag, particularly on Firefox:

When I type in anything, the text is refreshed and becomes visible only following mouse movement. I don't experience this with the same setup when I use Sway as the compositor.

**Comment by project-repo** [comment]
Thank you for the bug report! Indeed we actually noticed this once
before... At this time however, I seem to remember that the same was
happening under Sway leading us to believe that it was a firefox bug. I
can no longer reproduce this though, so we'll be looking into this
again.

As a temporary workaround, try setting the environment variable
`MOZ_ENABLE_WAYLAND=0`. At least for me, this prevents the bug from
occurring.

cheers
project-repo

**Comment by kinleyd** [comment]
Yes, that does it, as does removing 'MOZ_ENABLE_WAYLAND=1' from ~/.bashrc.
There is one side effect of that though: the mouse pointer icon becomes
large! Let me see if that resolves itself.

**Comment by kinleyd** [comment]
I'm not sure if it is somehow connected to Firefox/Wayland but I've been hit with a number of crashes when running Cagebreak, and again, these have not occurred on the same setup running Sway. One of the side effects is Firefox opening new instances indefinitely.

The two notable error references are to an old GTK bug and the other to a bug related to the use of emacs in daemon mode. However, I have not been able to identify the specific trigger nor replicate it, but  once I do that I will provide an update.

**Comment by project-repo** [comment]
Hi,
we have probably fixed this issue in the latest commit on the development branch.
If you'd like, you can check it out there. We aim to release this within the next few days.

Thanks again!
project-repo

**Comment by kinleyd** [comment]
Awesome, thanks for the update!

**Comment by project-repo** [comment]
This issue has been resolved in release 1.8.2. I am closing this issue.
Feel free to reopen if the behaviour persists on your setup.

Thank you for helping to improve cagebreak!

cheers
project-repo

**Comment by kinleyd** [comment]
Installed release 1.8.2 and confirmed that the issue is resolved on my system. 
Thank you!
