### ISSUE TITLE
Huge mouse pointer/cursor icons

### ISSUE THREAD

**Issue by kinleyd** [project-repo/cagebreak#16]
This is somewhat related to issue #10. After the fix to the screen refresh lag in Firefox, my mouse pointer/cursor is very frequently (but not always) huge and hard to look at. This occurs when hovering over all applications, not just Firefox.

Also, and I'm not sure if it is related, even with an 'export MOZ_ENABLE_WALYAND=1' setting, xlsclients reports Firefox as a Xorg application and not Wayland as I would expect.

**Comment by project-repo** [comment]
Unfortunately I am unable to reproduce the issue with the
pointer/cursor.

However, in my case firefox is also not showing up in xlsclients...
How are you setting `MOZ_ENABLE_WAYLAND`? Note that running
`export MOZ_ENABLE_WAYLAND=1` from one terminal and firefox from a
different one (or from cagebreak directly) does not work, this command
must be executed before cagebreak is started or in the same terminal
as the one you are starting firefox in.

cheers
project-repo

**Comment by project-repo** [comment]
Is this still relevant?

**Comment by kinleyd** [comment]
Yes, even with multiple updates to Firefox the oversized mouse cursor problem persists.

**Comment by project-repo** [comment]
So I played around with this a bit more yesterday (I was having a
similar problem with an xwayland application). What solved it for
me was setting the environment variable `XCURSOR_SIZE` to 1. Of course,
this will most likely only work on xwayland and as it seems you are not
running firefox under xwayland, it may well be that this does not help.
But just in case, could you try running `XCURSOR_SIZE=1 firefox` or
exporting `XCURSOR_SIZE=1` before starting firefox?

Cheers,
project-repo

**Comment by kinleyd** [comment]
Though I'm still not using xwayland, starting with 'XCURSOR_SIZE=1 firefox' on the command line does yield Firefox with normal size icons. I've only tried this a couple of times so far, so I will update my experience with a bit more usage. Thanks.

**Comment by kinleyd** [comment]
Hi,
I took a look again and find that though the icons are still noticeably bigger on Cagebreak/Wayland than it is on my Xorg setup, they don't categorize as huge or humongous anymore. I think I could live with it.
Thanks!

**Comment by project-repo** [comment]
Thank you for your response.

Could you maybe provide screenshots from both your X setup
and your cagebreak setup so that we can evaluate whether changes
are necessary?

cheers
project-repo

**Comment by kinleyd** [comment]
I couldn't take screen shots that included the cursor so I took shots with my phone from roughly the same distance and cropped/merged them for easier comparison. The bigger cursor is from Cagebreak/Wayland and the other is EXWM/Xorg:
![cursor_sizes](https://user-images.githubusercontent.com/1420223/194704101-f87a7378-623a-419f-86da-71504a0926aa.jpg)

**Comment by project-repo** [comment]
Hi kinleyd,

sorry for not responding for such a long time.

We have an idea for a solution, which we are currently exploring: Namely
we aim to provide a configuration allowing the user to scale
the mouse size.

We are now looking into whether we can implement such a solution.

Would this be satisfactory for you?

cheers
project-repo

**Comment by kinleyd** [comment]
Hey, no problem at all. I appreciate what you are already doing.

Yes, it would be great if you could do that! Thank you.

**Comment by project-repo** [comment]
Hi kinleyd

So, we looked into this and our conclusions are as follows: As it turns
out, there is no general way for defining cursor sizes in wayland since
it uses client-side cursors.

However, most applications respect the environment variables `XCURSOR_SIZE` and `XCURSOR_THEME` when setting the cursor image. So, running `export XCURSOR_SIZE=1` before starting cagebreak should pick the smallest available cursor size. Alternatively, the smallest available cursor size is probably 16x16 or 8x8, so you can replace `1` with `8` or `16` and see if that changes the result.

Does this behave as you would expect? If not, are you applying any scaling to the screen?

Cheers and merry Christmas
project-repo

**Comment by kinleyd** [comment]
Thanks, that works. 
However, since I have Emacs starting as a service before Cagebreak, the cursor remained large on Emacs windows. So I had to modify the systemd unit for Emacs to include 'Environment=XCURSOR_SIZE=1' as well, and that fixed it for Emacs as well. :)

**Comment by project-repo** [comment]
Hi kinleyd,

it is great that it works for you now. Thank you for mentioning the
intricacies with emacs, we will include a note in the FAQ to remind
people who use any sort of daemon-based programs under Cagebreak.

cheers
project-repo

**Comment by kinleyd** [comment]
You are most welcome, and thank you for the work you are doing!

**Comment by project-repo** [comment]
Hi kinleyd,

the FAQ entry we mentioned above is part of release 2.0.0.

cheers
project-repo
