### ISSUE TITLE
Is there a way to change the font and display time for message window?

### ISSUE THREAD

**Issue by bda65hp** [project-repo/cagebreak#19]
Hi,
Is there a way to easily change de font? "monospace 10" are too small for my eyes. I've changed them in message.c but can you add a configuration option, please?
Same for the display time of these window. They sometimes disappear too fast (mainly time).
May be a config for the background and foreground color of the message window too?

cagebreak is great :)

**Comment by project-repo** [comment]
No, there is currently no easy way to change the font size, background or display
time of the message.

Adding these ideas as a command is a good idea though.

To summarize, the release pertaining to #19 will presumably introduce a
command for configuring the cagebreak messages. This command will be
able to set the following:

  * [ ] Font size
  * [ ] Font colour
  * [ ] Background colour
  * [ ] Display time of message

Another, related, idea would be to have an interface for sending
arbitrary messages over the socket which are then displayed by
cagebreak. This may also be added to the above features.

We're glad to hear that you enjoy cagebreak! Thank you for helping to
make it even greater.

cheers
project-repo

**Comment by bda65hp** [comment]
Awesome :)
Displaying time in locale format (or configurable) will be great too ;)

**Comment by project-repo** [comment]
We pushed some code to development implementing this in https://github.com/project-repo/cagebreak/commit/348925e30a350ee5a9ab60e6364f258654a02f68 (configuration) and https://github.com/project-repo/cagebreak/commit/f12a16160c86325258dbed185317300358f7d3d1 (message command). Sorry for not writing this much sooner. However, at least it will be part of the upcoming release.

cheersproject-repo

**Comment by project-repo** [comment]
This issue has been resolved in release 1.9.0.

I am closing this Issue.

Please feel free to reopen if problems persist or open a new issue.

cheers
project-repo
