### ISSUE TITLE
How to disable a output?

### ISSUE THREAD

**Issue by iyzsong** [project-repo/cagebreak#2]
Hello, I have two outputs (or heads) eDP-1 and HDMA-A-1, and always want to disable eDP-1, how to do it?

Thank you!

**Comment by project-repo** [comment]
Hi,
This is currently not implemented in cagebreak, the main reason for this being that no one thought of it/had a use for it earlier. I've started looking into a potential implementation of this though similar to sway and I think it should be possible so we may soon support this.
In the meantime, a possible workaround is just setting the background color to black.

Cheers
project-repo

**Comment by iyzsong** [comment]
Okay, after some search, it turn out that my output can be disabled by add `video=eDP-1:d` to the kernel arguments.
https://wiki.archlinux.org/index.php/Kernel_mode_setting#Disabling_modesetting

Also I tried `kanshi` (https://wayland.emersion.fr/kanshi), but it complain that  `wlr-output-management` is not implmented.  Maybe it's a good idea to implement that extension so that `kanshi` can work with `cagebreak`.

Feel free to close this issue since outputs can be disabled by a linux kernel argument, thank you!

**Comment by project-repo** [comment]
> Okay, after some search, it turn out that my output can be disabled by add `video=eDP-1:d` to the kernel arguments.
> https://wiki.archlinux.org/index.php/Kernel_mode_setting#Disabling_modesetting
Do you mean disabling the output on boot via KMS, or dynamically? Anyways, I've implemented an option for cagebreak to disable an output (see `disable_output` branch, the code hasn't gone through much testing yet, so no garantees), so if you like you can test that too. The syntax is `output <output_name> enable` and `output <output_name> disable` (in the config file or when attached to the cagebreak socket), if you see anything, let us know.
> Also I tried `kanshi` (https://wayland.emersion.fr/kanshi), but it complain that `wlr-output-management` is not implmented. Maybe it's a good idea to implement that extension so that `kanshi` can work with `cagebreak`.
I've looked into this a bit, not sure yet whether we want to implement that protocol, feel free to open another issue to track progress on this.

**Comment by iyzsong** [comment]
>  Do you mean disabling the output on boot via KMS, or dynamically?
Hello, I disabled it on boot via KMS, and can’t find a way to
dynamically disable it via kernel.

>  Anyways, I've implemented an option for cagebreak to disable an
>  output (see disable_output branch, the code hasn't gone through much
>  testing yet, so no garantees), so if you like you can test that
>  too. The syntax is output <output_name> enable and output
>  <output_name> disable (in the config file or when attached to the
>  cagebreak socket), if you see anything, let us know.
I build the ‘disable_output’ branch, and it works!  Both via
~/.config/cagebreak/config or the CAGEBREAK_SOCKET, thank you!

**Comment by project-repo** [comment]
> Hello, I disabled it on boot via KMS, and can’t find a way to dynamically disable it via kernel.

Ah yes, that's what I thought too. In this case, the new feature is still an improvment.

> I build the ‘disable_output’ branch, and it works! Both via ~/.config/cagebreak/config or the CAGEBREAK_SOCKET, thank you!

Glad to hear! No problem, thank you for the feedback and for reporting. This feature will be included in the next release, so I'm closing the issue.
Cheers,
project-repo
