### ISSUE TITLE
config issue - continued

### ISSUE THREAD

**Issue by kinleyd** [project-repo/cagebreak#22]
This is with reference to issue #13. Earlier I thought changes to my setup were working but I find in fact that it isn't.

Based on advice in #13 I have a call to a shell script from my config file which is currently setup this way:

echo "prevscreen" | nc -i 1 -U $CAGEBREAK_SOCKET
emacsclient -a "" -c -F "((name . \"dired\"))" &
sleep 1 &
firefox &disown
sleep 10 & 
echo "nextscreen" | nc -i 1 -U $CAGEBREAK_SOCKET
emacsclient -a "" -c -F "((name . \"cider\"))" &
sleep 1 &
echo "nextscreen" | nc -i 1 -U $CAGEBREAK_SOCKET
emacsclient -a "" -c -F "((name . \"org\"))" &
sleep 1 &
echo "prevscreen" | nc -i 1 -U $CAGEBREAK_SOCKET

However, calls to Cagebreak's screen commands continue to execute immediately and don't wait for shell commands to time out.

**Comment by project-repo** [comment]
I suspect that your problems stem from to use of `&` after the sleep
commands. This forks a shell which executes the sleep command and
the parent shell immediately executes the next command.

If you use `&` after all relevant commands, the behaviour will be
similar to the behaviour you mentioned in #13 as the fork makes
sleep non-blocking.

Imho, this does not seem to be an issue with cagebreak but an issue with
the shell script. (You can test this by replacing the commands
influencing cagebreak by other commands and observing the timing.)

I am closing this issue for right now, if the problem persists feel free
to write back here though.

cheers,
project-repo

**Comment by kinleyd** [comment]
⁣How could I let the & slip with sleep? :facepalm:

Thanks.
