### ISSUE TITLE
Missing include guard breaks building without xwayland

### ISSUE THREAD

**Issue by tdaniel22** [project-repo/cagebreak#24]
The `wlr/xwayland.h` include in `output.c:32` is missing an `#if CG_HAS_XWAYLAND` guard, which breaks building without xwayland.

**Comment by project-repo** [comment]
Hi,
Thanks for reporting, seems like this has gone unnoticed for quite some time! There should be a fix on the development branch now if you feel like checking it out.
cheers
project-repo

**Comment by tdaniel22** [comment]
Thanks! Compiles and works as expected.

**Comment by project-repo** [comment]
This issue has been resolved in release 1.9.0.

Please feel free to reopen if problems persist or open a new issue.

cheers
project-repo
