### ISSUE TITLE
launching programs

### ISSUE THREAD

**Issue by apluos** [project-repo/cagebreak#32]
What is the "proper way" to launch a programs, since cagebreak doesn't support "traditional" launchers, and launching from the terminal leaves a terminal unusable?

**Comment by project-repo** [comment]
There are multiple ways to launch external programs in cagebreak.

  * Using a terminal emulator is a perfectly valid way to launch
    applications. If you want to be able to close the terminal
    you used to start the program, you may use `&disown`, which should
    be available in every shell.
  * Using the `exec` command in the cagebreak config, it is possible to
    launch programs when cagebreak is started. Moreover, as this command
    can be combined with commands such as `bind`, it can be used to
    create custom keybindings which execute external programs. (See also
    the man page `cagebreak-config`).
  * All commands mentioned previously are also available over the socket
    which allows the creation of (arbitrary) keybindings on the fly and
    a fortiori keybindings running arbitrary commands.

cheers
project-repo

**Comment by apluos** [comment]
thank you
