### ISSUE TITLE
Feature request: custom events via IPC

### ISSUE THREAD

**Issue by sodface** [project-repo/cagebreak#45]
If process A is already listening for cagebreak events via IPC, it would be helpful if process B could relay a custom event through the socket to process A.

[Herbstluftwm](https://herbstluftwm.org/herbstluftwm.html) has this functionality via `emit_hook`.

This can sort of be accomplished by abusing the `definemode` command with the mode being the message to pass (without spaces) to the process listening to IPC events. The modes are saved by cagebreak though, so these will quickly stack up and there doesn't seem to be a complement `deletemode` command. But this isn't the purpose of `definemode` anyway.

**Comment by project-repo** [comment]
Hi sodface

this feature seems to be a good idea. We will implement it in due course.

The implementation will probably take the shape of a command

```
command "string"
```

where the string is the message which will be sent over the socket
(using the json structure as usual).

cheers
project-repo

**Comment by project-repo** [comment]
Hi sodface,
we pushed a new branch `feature/custom_socket_event` yesterday, which
implements this. If you like, you can give it a spin: the feature branch
introduces a new command `custom_event` with the same syntax as
`message`. Documentation has not yet been written.
Cheers,
project-repo

**Comment by sodface** [comment]
Working for me, nice! Thanks again.

**Comment by project-repo** [comment]
Fixed in 2.2.0
