### ISSUE TITLE
How do I change the color of the message box?

### ISSUE THREAD

**Issue by VehementHam** [project-repo/cagebreak#51]
The box in the top right corner displays messages like the time and workspace. I want the color to be consistand with my theme. How do I change it?

**Comment by project-repo** [comment]
You can find this information in the man pages: https://github.com/project-repo/cagebreak/blob/master/man/cagebreak-config.5.md#commands.
The `configure_message` command should do the trick.

**Comment by VehementHam** [comment]
Thanks.
