### ISSUE TITLE
SwayBG Returns Error

### ISSUE THREAD

**Issue by VehementHam** [project-repo/cagebreak#52]
When I run `swaygb`, it returns the error `[main.c:587] Missing a required Wayland interface`.

**Comment by project-repo** [comment]
Hi VehementHam

Yes, this is known and is due to the fact that cagebreak does not
implement the layer-shell protocol. See also #6. We currently don't plan
to support this in the foreseeable future, as it adds too much
complexity for too little gain.

Cheers
project-repo

**Comment by project-repo** [comment]
For future visitors: Cagebreak now supports the layer-shell protocol, so swaybg should work for Cagebreak. If not, please open a new issue.
Cheers,
project-repo
