### ISSUE TITLE
Toggle Top Mode Binding

### ISSUE THREAD

**Issue by VehementHam** [project-repo/cagebreak#53]
Hey I am wondering how to set a keybind to togglig top mode. For exaple C-t enters top mode and exits after I do something. If I want to do multiple things in a row it is more efficent to also have a keybind to toggel top mode like resize.

**Comment by project-repo** [comment]
Hi VehementHam
Please consult the config man page. You should be able to achieve what
you want using the `setmode` command.

Cheers
project-repo

**Comment by VehementHam** [comment]
Here's the solution:
```
definekey top A-t setmode root
bind Escape setmode top
```

**Comment by VehementHam** [comment]
f
