### ISSUE TITLE
Feature Request: Scratchpad Functionality

### ISSUE THREAD

**Issue by VehementHam** [project-repo/cagebreak#55]
Unless there is already a way to use scratchpads, I think that it would be a good feature to add to the window manager.

**Comment by project-repo** [comment]
Hi VehementHam

We like to keep it simple and propose the following:

```
bind <key> exec /usr/bin/your-terminal-emulator -e $EDITOR
```

We will not implement a specific scratchpad functionality in our effort to keep functionality minimal.

cheers
project-repo
