### ISSUE TITLE
Expanding a Window (Reverse of Splitting)

### ISSUE THREAD

**Issue by VehementHam** [project-repo/cagebreak#57]
I am filing this issue after, once again, accidentally splittng the window the wrong way. Not only that but I often accidentally split a window when I try to press the time keybind. Regardless of accidents, there are still [plplenty of occasions where I open a window and then close it (and then there is just an empy space). Reconfiuring my layout is extremely inefficient without this feature. Does it exist, or is it possible to script it?

**Comment by sodface** [comment]
Does the `only` command get you what you want? From the man page:

> only Remove all splits and make current window fill the entire screen

The default keybind is Q, so <ctrl-t><shift-q>

**Comment by project-repo** [comment]
Thanks @sodface for helping out!

Regarding the removal of a single split (in case the `only` command as
suggested by @sodface doesn't suffice), this is an open problem and has
already been discussed in #21.

However, in contrast to the "undo" mentioned in the latter issue, you
(@VehementHam) seem to specifically be proposing a merge of two tiles,
which is an interesting idea, thanks! Maybe that would be a viable
alternative to implementing an "undo" (@josegpt)? However, it carries
with it its own problems: For example, what should happen if you attempt
to merge a tile which is half the size of the screen with one that has
the full height? If you have specific ideas as to how exactly an
implementation should look like, feel free to comment on #21.

cheers
project-repo
