### ISSUE TITLE
Rough script for grim screenshots with region selection

### ISSUE THREAD

**Issue by sodface** [project-repo/cagebreak#64]
Presenting for feedback. Feel free to close at your discretion. Could answer:
https://github.com/project-repo/cagebreak/issues/56

Explanation:
- bind root mode key g to run the grim.sh script
- define a keymap mode called "grim"
- when in grim mode, define g key to dump state
- define Escape to return to top mode

config:
```
bind g exec killall -9 grim.sh; $HOME/.config/cagebreak/grim.sh
definemode grim
definekey grim g dump
definekey grim Escape setmode top
```
To take a screenshot (with my key bindings which are mostly default)
- ctrl-t + g to fire the grim.sh script
- grim.sh (below) sets grim keymap mode
- now in grim mode, place cursor/pointer at top left corner of desired region and press g
- move cursor/pointer to bottom right corner of desired region and press g
- screenshot is taken with default name and saved in $HOME
- if you just press the g key twice without moving your cursor/pointer, the entire current output will be captured
- script returns to top mode after screenshot is taken

note: this is _not_ a click, hold and drag sequence to draw an imaginary box, it's just based on the pointer coordinates when the g key is pressed. So just get the pointer in the top left of the imaginary bounding box and press g so the script can capture the first set of coordinates, then repeat for the bottom right corner. 

The grim.sh script:
```
#!/bin/sh
source $HOME/.config/cagebreak/cb_script_header.sh

echo "setmode grim" >&3

while IFS= read -r -d $'\0' event
do
	if echo "${event}" | grep -q "cursor_coords"; then
		read x1 y1 < <(echo "${event#*cursor_coords}" | awk -F":" '{print int($3)" "int($4); exit}')
		break
	fi
done <&4

while IFS= read -r -d $'\0' event
do
	if echo "${event}" | grep -q "cursor_coords"; then
		read x2 y2 < <(echo "${event#*cursor_coords}" | awk -F":" '{print int($3)" "int($4); exit}')
		break
	fi
done <&4

w=$(( x2 - x1 ))
h=$(( y2 - y1 ))

if [ ${w} -eq 0 ]; then
	co=$(echo "${event#*curr_output}" | awk -F'"' '{print $3; exit}')
	grim -o "${co}"
else
	grim -g "${x1},${y1} ${w}x${h}"
fi

echo "message screenshot complete" >&3
sleep 1
echo "setmode top" >&3
```

The rough parts:
- probably fragile use of awk instead of jq
- if you change your mind and escape out of grim mode after starting but before finishing the sequence, the script will stay running until you enter grim mode next time (hence the killall command in the keybind)
- the region selection is not a visual selection, you have to imagine the box you are defining when pressing the g key for each corner
- I don't like using sleep but without it, the "screenshot complete" message just flashes very quickly, I guess because the script exits and disconnects from the IPC?

**Comment by project-repo** [comment]
Hi sodface

Thanks for sharing, that indeed looks very interesting! If you are
willing to contribute this to the repository, we would like to slightly
rework the script and add it to our `example_scripts/`.
Are you allowed and willing to let us publish your modified work under
the MIT License?

In any case, we'll keep this issue open for now, since atm our
development resources are rather occupied with getting cagebreak to run
with wlroots 0.17.

Taking a quick look at your script, one hint that might be useful to you
is that you can actually detect mode changes over the socket and
terminate accordingly without the need to use "killall" (see the
"switch_default_mode" event).

Cheers
project-repo

**Comment by sodface** [comment]
> Are you allowed and willing to let us publish your modified work under
the MIT License?

Yes indeed!

> wlroots 0.17

Understood.

> see the "switch_default_mode" event

I'll check it out, thanks!!

**Comment by sodface** [comment]
Here's another, possibly uglier, version which attempts to incorporate your advice to test for the "switch_default_mode" event and remove `killall` from the config.

config:
```
bind g exec $HOME/.config/cagebreak/grim.sh
definemode grim
definekey grim g dump
definekey grim Escape setmode top
```
grim.sh
```
#!/bin/sh
source $HOME/.config/cagebreak/cb_script_header.sh

echo "setmode grim" >&3

i=0
while IFS= read -r -d $'\0' event
do
	type="$(echo "${event:21}" | awk -F'"' '{print $1; exit}')"
	if [ "${type}" == "switch_default_mode" ]; then
		mode="$(echo ${event##*mode\"} | awk -F'"' '{print $2; exit}')"
		[ "${mode}" != "grim" ] && break
	elif [ "${type}" == "dump" ]; then
		[ ${i} -gt 0 ] && break
		read x1 y1 < <(echo "${event#*cursor_coords}" | awk -F":" '{print int($3)" "int($4); exit}')
		i=$(( i + 1 ))
	fi
done <&4

if [ "${mode}" == "grim" ]; then
	read x2 y2 < <(echo "${event#*cursor_coords}" | awk -F":" '{print int($3)" "int($4); exit}')
	w=$(( x2 - x1 ))
	h=$(( y2 - y1 ))

	if [ ${w} -eq 0 ]; then
		co=$(echo "${event#*curr_output}" | awk -F'"' '{print $3; exit}')
		grim -o "${co}"
	else
		grim -g "${x1},${y1} ${w}x${h}"
	fi

	echo "message screenshot complete" >&3
	sleep 1
	echo "setmode top" >&3
fi

pkill -9 -P $$
```
I've had some issues with an `nc` process lingering around after the script exits which also drives the cagebreak process to 100% on one core (similar to a previous issue) which is the reason for the `pkill` at the end of the script.

**Comment by sodface** [comment]
And for another option, I tested out a couple of screenshot tools today and found [Satty](https://github.com/gabm/Satty) to be really good!

Add to cagebreak config:

```
bind e exec $HOME/.config/cagebreak/satty.sh
```

satty.sh:

```
#!/bin/sh
source $HOME/.config/cagebreak/cb_script_header.sh

echo "dump" >&3
IFS= read -r -d $'\0' event <&4

co=$(echo "${event#*curr_output}" | awk -F'"' '{print $3; exit}')
grim -t ppm -o "${co}" - | satty -f - --early-exit --output-filename $(date +'%Y%m%d_%Hh%Mm%Ss_satty.png')

pkill -9 -P $$
```

This gives you a screenshot of the current output opened in Satty for editing, as pictured in this screenshot:

![20231219_19h24m40s_grim](https://github.com/project-repo/cagebreak/assets/46695384/51ad3a1b-617a-4dbf-8ff3-7665c6c3a0dc)

And when you save, Satty exits immediately letting you quickly get back to what you were doing. This screenshot is what was saved from above editing:

![20231219_19h23m47s_satty](https://github.com/project-repo/cagebreak/assets/46695384/22c5f5ee-f63d-4013-8171-c96e002ac222)

**Comment by sodface** [comment]
I should note that while Satty is very nice, it pulls in gtk4.0 and all it's dependencies (47 additional packages on my Alpine machine).

**Comment by sodface** [comment]
One more option...

As I said above, Satty is nice but it has a lot of dependencies so I came up with another option using `grim` and `mpv` with a lua script.

Why?

- I figure a lot of Cagebreak users will already have `mpv` installed
- I've been working on other projects with mpv/lua recently so why not try it here?

config:

```
bind c exec mpv --idle --script=$HOME/.config/cagebreak/cropshot-socket.lua
```

The first version I did used an intermediate shell script to get the dump, parse for current output, take the screenshot with `grim` and then launch `mpv` for cropping, which worked fine but I revised it to remove the shell script altogether and do everything from the lua script. This does require the small additional dependency of `lua-socket`.

So the requirements are:

- mpv media player
- lua-socket
- grim

Basic operation is to use `ctrl-t c` (or however you define the keybinding) which launches mpv in idle mode. At this point mpv is started and loaded our script but hasn't created a window, so nothing is visible yet. The script connects to the Cagebreak socket, gets the dump, parses out the current output and then uses grim to create a full screen screenshot to a temporary file.

I used a temporary file because cropping with mpv wasn't working with grim piping to mpv's stdin.

Once grim has created the temp file, mpv loads it. The mpv window is now visible but since this all happens so quickly and the image mpv is displaying is the same as what was on the screen, it still doesn't look like anything has happened, but you should be able to click and drag with your mouse to draw a crop box.

Once you draw your box, press `c` again to perform the crop and have mpv save a screenshot of the cropped image in your home directory. The cropped image will be displayed by mpv for 1 second and you should see the normal mpv screenshot message before mpv automatically exits.

Something like this (I know Firefox has a builtin screenshot tool, these are just for illustration):

![mpv-shot0007](https://github.com/project-repo/cagebreak/assets/46695384/e656d602-a8b1-408d-acab-c90c55ffcf4f)

![mpv-shot0010](https://github.com/project-repo/cagebreak/assets/46695384/42b9e220-f97c-49cc-9ea8-70c0aed6cf13)

Here's the script. No comments, no error catching, no points for style etc. but it seems functional in my limited testing. Remove the .txt extension.

[cropshot-socket.lua.txt](https://github.com/project-repo/cagebreak/files/13760923/cropshot-socket.lua.txt)

**Comment by sodface** [comment]
Unfortunately, my testing was a bit lacking. The current version of `cropshot-socket.lua` doesn't really work when there is more than one tile (split) on the current workspace. The cropping geometry is off if mpv isn't full screen.

I think there's a few ways to fix this:

1. Save the configuration of the current workspace, send an `only` command to remove the splits so mpv opens full screen, then restore the workspace to the original config when mpv exits.
2. Open mpv on a workspace that's either empty or has no splits and then switch back to the original workspace on mpv exit. This assumes there's a workspace available that meets the criteria.
3. Add a new workspace and open mpv there.

I haven't tried any of these yet but my first thoughts are that 1 will be the most "work" but if done correctly should always be reliable.  

2 is probably the easiest but is based on an assumption of workspace availability that may not be true.  

3 also assumes that the number of configured workspaces is less than the maximum (30) which might be false. Adding a workspace also seems a bit intrusive especially since there doesn't seem to be a command to remove a workspace which I would want to do on mpv exit.

Maybe a combination of 1 and 2. Do 2 first and fall back to 1, but if I have to figure out 1 anyway then I might as well just use 1.

**Comment by sodface** [comment]
Ok, here's an updated lua script for mpv that implements option 3 above. I used mpv's builtin json parsing utility function to get several values from the dump output: current workspace, number of workspaces, and current output.

That's probably all I'll do with this, honestly, it was a lot of mucking about just to be able to draw a visual crop box. The script [in this post](https://github.com/project-repo/cagebreak/issues/64#issuecomment-1833075252) is much simpler and just as effective, albeit without the visual box.

Obviously, this isn't what mpv was meant for so not the right tool for the job, but it does maybe provide a crude example of using lua to interact with the Cagebreak socket.

[cropshot-socket.lua.txt](https://github.com/project-repo/cagebreak/files/13763756/cropshot-socket.lua.txt)

**Comment by project-repo** [comment]
Hi sodface

We have thought about this a bit and I think we will be settling with
a rather simple solution:

There are different image editors to crop and paint images
and each user may have their favourite. Therefore, we propose to
provide a script which takes as an argument a single bash command
(see the attached script). This command will then be executed with the
path to a file containing a screenshot as a last argument. For instance,
presuming you have `gwenview` installed, you could call the script as:
`bash screenshot_script gwenview`

Does that work for you?

It seems you have tested many more editing/cropping tools than we have, could you add
them to our script as comments?

screenshot_script
```
#!/bin/bash
# Copyright 2023, project-repo, sodface and the cagebreak contributors
# SPDX-License-Identifier: MIT

source "$(dirname "${BASH_SOURCE[0]}")/cb_script_header.sh"

if [[ ${#} -lt 1 ]]
then
        echo "Expected a single command line argument specifying the command to edit the screenshot."
        exit 1
fi

edit_cmd="${1}"

echo "dump" >&3
IFS= read -r -d $'\0' event <&4

co="$(echo "${event:6}"|jq -r ".curr_output")"
tmpfile="$(mktemp)"
grim -t png -o "${co}" "${tmpfile}"
bash -c "${edit_cmd} \"${tmpfile}\""
wl-copy < "${tmpfile}"
rm "${tmpfile}"

```
Cheers
project-repo

**Comment by sodface** [comment]
> Does that work for you?

It does, thanks for taking the time to review and post a more sane solution. The more I worked on this (for fun as I've had some free time) the more I came to question what I was trying to accomplish. Initially it was just to provide a method to get a cropped screenshot with just grim, quickly with minimal fuss and disruption. Once you want to start adding text and other annotations to the screenshot, you should probably use an application designed for that purpose.

> It seems you have tested many more editing/cropping tools than we have, could you add
them to our script as comments?

As I said above, Satty is nice but has a lot of dependencies, if one cares about such things (I kinda do). Beyond that, the only other one I tested was Swappy which provides basic markup tools but doesn't do cropping, I think you are expected to feed it a pre-cropped image.

So I probably haven't tested more tools than you have! For just basic cropping, opening the screenshot in Firefox is an option too.

I think we should probably just go with your script as-is and close this issue out?

**Comment by project-repo** [comment]
Hi sodface

Thanks for your comments. Please leave the issue open until release
2.3.0 is published (when we plan to include the script described above).

cheers
project-repo

**Comment by sodface** [comment]
Apologies for going off on tangents in the issue comments... but it was sort of bugging me that you have to do all the fifo stuff for a one shot command like dump.

This was the best I could come up with for a (long) one-liner:

```
dump=$(echo dump | nc local:$CAGEBREAK_SOCKET | xargs -0n1 printf '%scg-ipc\n' | awk -v RS="cg-ipc" 'NR==2{print;system("pkill -nx nc")}')
```

**Comment by project-repo** [comment]
Hi sodface

A script discussed here has been added with release 2.3.0.

I am closing this issue.

Cheers
project-repo
