### ISSUE TITLE
Dual monitors mirrored instead of extended with v2.2.2

### ISSUE THREAD

**Issue by sodface** [project-repo/cagebreak#66]
Hi, testing 2.2.2 on Alpine locally before submitting the package upgrade.

Cagebreak starts normally on my two monitor desktop however my right monitor is a mirror of the left. Pointer travel and coordinates in dump output seem correct for a two monitor extended desktop but an open application is displayed on both screens at the same time. I'm also unable to change outputs to the right monitor (eg. ctrl+t 2), when I do that, I do not see the "current output" message displayed and even though pointer travel is correct, I can't type, click, or otherwise interact with the mirrored application on the right monitor, it's as if it's a still image.

**Comment by sodface** [comment]
Here is my dump output with both monitors on and mirrored as described in post #1. Sorry for the multiple posts, I would just edit the first post but I'm pretty sure you don't see the edits via email.

[cb-2.2.2-dump.txt](https://github.com/project-repo/cagebreak/files/13545960/cb-2.2.2-dump.txt)

**Comment by project-repo** [comment]
Hi sodface

thank you so much for submitting this report.

We have implemented a tentative fix on `hotfix`. Does this resolve your issue?

cheers
project-repo

PS: Thank you very much for not editing your answer, this is much more convenient for us.

**Comment by sodface** [comment]
> Does this resolve your issue?

Yes, looking good!

**Comment by project-repo** [comment]
Hi sodface

Thank you again for raising this issue.

The tentative fix from yesterday is released with 2.2.3.

cheers
project-repo
