### ISSUE TITLE
Firefox 120.0.1 window position issue

### ISSUE THREAD

**Issue by sodface** [project-repo/cagebreak#67]
I'm not sure if this is a Cagebreak issue really but curious if anyone else is seeing this? I just upgraded my laptop to Alpine 3.19 and Firefox 120.0.1 is offset right and down. Top left corner isn't 0,0 in other words, more like 30,30 or something which pushes the right and bottom off the screen.

![20231217_01h03m14s_grim](https://github.com/project-repo/cagebreak/assets/46695384/093bc082-5c0f-426e-853a-147850372565)

**Comment by project-repo** [comment]
Hi sodface

We will investigate further but some preliminary tests on Arch Linux with
Firefox 120.0.1 (the version you meant, right?) could not reproduce this
issue.

Please report back if you find any more context or can reproduce this on
a different setup (e.g. other OS, other compositor, etc.).

cheers
project-repo

**Comment by sodface** [comment]
> Firefox 120.0.1 (the version you meant, right?)

Yes, I edited the issue but you probably aren't seeing that from where you replied from (as we've discussed before!) sorry about that.

I posted this issue late last night without much troubleshooting. I'm on my desktop now running the same versions of everything and all seems fine, so I'll try it on a different laptop and see if I can narrow it down.

Desktop screenshot (courtesy of grim script):

![20231217_09h06m23s_grim](https://github.com/project-repo/cagebreak/assets/46695384/9f9f4aad-9c51-48de-a11e-e83a9421f8f8)

**Comment by sodface** [comment]
Ok, I figured it out. My desktop, which was fine, somehow had the advanced prefs setting `browser.tabs.inTitlebar` changed from the default value of 2 to 0. My laptop was set to the default value and changing it to 0 immediately fixed the issue.

![20231217_09h59m04s_grim](https://github.com/project-repo/cagebreak/assets/46695384/813c2cfc-a63f-4273-99b6-d7a86a32b3fc)

**Comment by sodface** [comment]
Closing.
