### ISSUE TITLE
Suggestion: Change cursor to square when waiting for a key

### ISSUE THREAD

**Issue by ghost** [project-repo/cagebreak#7]
I personally found quite useful when I started with ratpoison to have the cursor change when the escape sequence is pressed and the wm is waiting for a key.

If this ratpoison behaviour is something you think would fit your vision for cagebreak it would be nice to have it :)

**Comment by project-repo** [comment]
Hi nipsis,
Thanks for your suggestion! I'm not sure though if we will be adding
this feature to cagebreak: I do also see the benefit of having the
cursor change when cagebreak is waiting for a key. However, if I
remember correctly it is a bit of a hassle to set the pointer from the
compositor and I don't think it would be worth writing ~200 lines of
code with potential bugs (not only in these lines but also in the additional
dependencies that we may need) only to have this feature.
We will be looking into what is needed though and let you know what we
decide.
Cheers,
project-repo

**Comment by nipsis** [comment]
No problem! Whichever way you go thank you for taking the time to read my feature requests!

**Comment by project-repo** [comment]
Hi

This is now implemented and will be merged to master in the next
release.

You can already check it out on the development branch.
https://github.com/project-repo/cagebreak/commit/baeb39579bd0ff98e58a8244d0db8c506719983c

cheers
project-repo
