### ISSUE TITLE
escape to root hitting S-d to set on in a nested session causes crash

### ISSUE THREAD

**Issue by 10leej** [project-repo/cagebreak#70]
Running in sway currently looking at testing the switch to cagebreak I changed the escape variable from C-t to L-t which seems to run fine.

However in looking to revert a split screen to an unsplit screen seems to cause cagebreak to crash. I can replicate this starting cagebreak from a TTY as well.

this is a fresah archlinux instalation pulling cagebreak in from the aur package v2.2.3 not the -bin package

```
joshua@desktop:~$ cagebreak
Cagebreak 2.2.3 is running on Wayland display wayland-0
Io error: Broken pipe (os error 32)
Error trying to flush the wayland display: Broken pipe (os error 32)
Io error: Broken pipe (os error 32)
Error trying to flush the wayland display: Broken pipe (os error 32)
thread 'smithay-clipboard' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smithay-clipboard-0.7.0/src/worker.rs:98:47:
called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: ExitFailure(1)
```

**Comment by 10leej** [comment]
Disregard I literally read my own config file wrong

**Comment by VehementHam** [comment]
Hi Josh.

**Comment by 10leej** [comment]
> Hi Josh.

this is not the place to reach me please take that over [here](https://10leej.com/contact)
