### ISSUE TITLE
Cagebreak crashes with mpv --fullscreen

### ISSUE THREAD

**Issue by sodface** [project-repo/cagebreak#78]
Running the latest development branch of Cagebreak on Alpine with wlroots 0.17.2. I don't normally run mpv with --fullscreen but I was working on something and added it for troubleshooting and was surprised that it caused Cagebreak to crash back to the tty.

Steps to reproduce:

This works:
```
mpv --idle --load-scripts=no --force-window
```
And just adding --fullscreen causes a crash:

```
mpv --idle --load-scripts=no --force-window --fullscreen
```
I tested starting the same mpv command with Cage, both from tty and from within a nested session inside of Cagebreak and both of those work fine.

Log entries:

```
 err: wayland.c:1448: failed to read events from the Wayland socket: Broken pipe
 err: wayland.c:2024: failed to roundtrip Wayland display: Broken pipe
 err: wayland.c:2024: failed to roundtrip Wayland display: Broken pipe
 err: wayland.c:2024: failed to roundtrip Wayland display: Broken pipe
N 21:22:49.487721  m-dbus-connection ../modules/module-dbus-connection.c:138:on_connection_closed: <WpDBusConnection:0x7f6074684870> DBus connection closed: Underlying GIOStream returned 0 bytes on an async read
warn: terminal.c:1831: slave exited with signal 1 (Hangup)
 err: wayland.c:1989: failed to flush wayland socket: Broken pipe
```

Can anyone reproduce?

**Comment by project-repo** [comment]
Hi sodface

Thanks for reporting this! We can indeed reproduce this and have
uploaded a fix to the development branch. Can you check whether this
resolves the issue?

Cheers
project-repo

**Comment by sodface** [comment]
Tested and working, thank you!

**Comment by WeNeedNothingMedia** [comment]
Ran into this problem with emacs and was about to submit a patch with the same fix that is on development branch... so also confirmed fixed.

**Comment by project-repo** [comment]
Has been resolved in a previous release.
