### ISSUE TITLE
Cannot bind multiple modifiers to key

### ISSUE THREAD

**Issue by 2110111-CTK45A** [project-repo/cagebreak#82]
I want to use the hotkey Alt+Shift+Down.
The Down arrow key, even with Shift held down, would not change the key symbol being sent, unlike how "k" would change to "K" with Shift held down.
Similarly, Ctrl+Alt+Key does not seem to work, or at least the documentation has not mentioned how one can create such keybinds.

I am not experienced with wlroots, but from my understanding of the source code, perhaps the switch case at around line 41 in parse.c can be modified to iterate through multiple modifiers before the hyphen.
For byspel, should I want the Alt+Shift+Right keybind, the string to be passed ought to be AS-Right.
Thereafter, the keybinding datatype might not even have to be modified.

For the moment I can just bind this function to a different key, but I would like to see the ability to bind as aforementioned in future releases.
If this is implemented, I believe the config manpage should be updated with correspondent examples.
Thank you.

**Comment by sodface** [comment]
Hi, this keybind works for me for Alt+Shift+Down:

```
definekey top A-S-Down exec brightnessctl s 5%-
```

**Comment by 2110111-CTK45A** [comment]
@sodface Your config works like a charm, thank you!
While I think there should still be an example in the manpage to be more clear to new users, it would be best to close this issue here.
