### ISSUE TITLE
Port to wlroots 0.18

### ISSUE THREAD

**Issue by fossdd** [project-repo/cagebreak#83]
wlroots 0.18 has been released two months ago: https://gitlab.freedesktop.org/wlroots/wlroots/-/releases/0.18.0

Is there a plan to migrate to the new version?

**Comment by project-repo** [comment]
Yes, cagebreak will be ported to wlroots 0.18, the code is already there on the development branch, if you need it now.
A release will likely take place later today (depending on your timezone).

cheers
project-repo

**Comment by fossdd** [comment]
Oh, I didn't notice there was a seperate development branch since it's not the default. Thanks for the notice and the upgrade!
