### ISSUE TITLE
compound bind-exec commands

### ISSUE THREAD

**Issue by eirenicon** [project-repo/cagebreak#86]
Is there a way to create bind exec commands that perform more than one task? For example, I'd like to both open an external application (eg. firefox) and have it open on workspace 2. I'd like to invoke the tasks at keybind execution time.  

Here's a what I have tried (without success):

C-t

bind w exec firefox && movetoworkspace 2
bind g workspace 8 && exec geany

Any help is most appreciated.

**Comment by project-repo** [comment]
This is indeed possible using the cagebreak socket. For example, you might add the line:
```
bind g exec path/to/script/below
```
to your cagebreak config. Then create a bash script in `path/to/script/below` containing:
```
#!/bin/bash
echo "workspace 8"|nc -U $CAGEBREAK_SOCKET -w 1
geany&disown
```
to achieve the intended effect of your second command. See also the `example_scripts/` directory and documentation for further information. Note in particular that you must run cagebreak with the `-e` option for this to work.

I hope that this was helpful and in any case feel free to follow up in case you still have questions!

Best
project-repo
