### ISSUE TITLE
Suggestion gaps, borders

### ISSUE THREAD

**Issue by nagy135** [project-repo/cagebreak#9]
Any chance we ll get gaps or selected frame border? I use terminals a lot and its kinda hard to know which on is selected since they share background.

**Comment by project-repo** [comment]
Hi,
Thanks for the feature request! Unfortunately I don't think that we
will be implementing this feature in the near future: First of all,
cagebreak already displays the currently focused tile when the tile
is switched. Moreover, as much as I know, most terminal emulators adjust
the cursor style when the terminal is focused so it should be possible
to detect the focused tile from this, right? In any case, we believe
borders and other decorations go against the design concept of cagebreak
which is aimed at being minimal and minimizing the "lost" screen space.
cheers,
project-repo

**Comment by nagy135** [comment]
I understand but unfortunatelly i totally got used to having hard red border around terminal in use and i cant get rid of this habbit...will have to try other wm, good luck!
